In [1]:
import numpy as np
data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])

# Task 1: Print the shape of data & Mean temperature

In [6]:
print("shape of data:", data.shape)

mean_temp =  data.mean(axis=1)  # axis=1 is mean calculated row-wise (per station)

print("Mean temperature per staion:", mean_temp)

shape of data: (4, 5)
Mean temperature per staion: [25.3  23.78 26.58 25.26]


# Task 2: Extract Temperature Above 28°C



In [8]:
mask = data > 28
high_temp = data [mask]
print("Temperature above 28°C:")
print(high_temp)

Temperature above 28°C:
[31.2 28.7 30.5 33.1 29.6 31.9 28.1]


# Task 3: Normalize Data between 0 & 1

In [16]:
# formula given: normalized = (data - data.min()) / (data.max() - data.min())

normalized = (data - data.min()) / (data.max() - data.min())

print("normalized dat:")   #Lowest temperature - 0
                           #Highest temperature - 1
print(normalized)


normalized dat:
[[0.32911392 0.10759494 0.87974684 0.72151899 0.49367089]
 [0.         0.34810127 0.83544304 0.57594937 0.29113924]
 [1.         0.77848101 0.06962025 0.42405063 0.66455696]
 [0.1835443  0.39240506 0.92405063 0.6835443  0.33544304]]
